import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const taskStatus = pgEnum("task_status", ["PLANNED","IN_PROGRESS","CODE_COMPLETE","PR_OPEN","MERGED","DEPLOYED","PROD_VERIFIED","DONE","BLOCKED"]);
export const agentKind = pgEnum("agent_kind", ["CHATGPT","CLAUDE","HUMAN","SYSTEM","OTHER"]);

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const projects = pgTable("projects", { id: uuid("id").defaultRandom().primaryKey(), slug: text("slug").notNull().unique(), name: text("name").notNull(), description: text("description"), githubRepo: text("github_repo"), vercelProjectId: text("vercel_project_id"), active: boolean("active").default(true).notNull(), ...timestamps });
export const milestones = pgTable("milestones", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), name: text("name").notNull(), position: integer("position").default(0).notNull(), ...timestamps }, (t) => [index("milestones_project_idx").on(t.projectId)]);
export const tasks = pgTable("tasks", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), milestoneId: uuid("milestone_id").references(() => milestones.id, { onDelete: "set null" }), title: text("title").notNull(), description: text("description"), status: taskStatus("status").default("PLANNED").notNull(), acceptanceCriteria: jsonb("acceptance_criteria").$type<string[]>().default([]).notNull(), ...timestamps }, (t) => [index("tasks_project_idx").on(t.projectId), index("tasks_status_idx").on(t.status)]);
export const agentRuns = pgTable("agent_runs", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), taskId: uuid("task_id").references(() => tasks.id, { onDelete: "set null" }), agent: agentKind("agent").notNull(), summary: text("summary"), startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(), finishedAt: timestamp("finished_at", { withTimezone: true }) });
export const pullRequests = pgTable("pull_requests", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), taskId: uuid("task_id").references(() => tasks.id, { onDelete: "set null" }), number: integer("number").notNull(), url: text("url").notNull(), headSha: text("head_sha"), mergedAt: timestamp("merged_at", { withTimezone: true }), ...timestamps });
export const deployments = pgTable("deployments", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), taskId: uuid("task_id").references(() => tasks.id, { onDelete: "set null" }), provider: text("provider").default("vercel").notNull(), externalId: text("external_id").notNull(), commitSha: text("commit_sha"), environment: text("environment").notNull(), status: text("status").notNull(), deployedAt: timestamp("deployed_at", { withTimezone: true }), ...timestamps });
export const verifications = pgTable("verifications", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), taskId: uuid("task_id").references(() => tasks.id, { onDelete: "set null" }), kind: text("kind").notNull(), passed: boolean("passed").notNull(), evidence: jsonb("evidence").$type<Record<string, unknown>>().default({}).notNull(), verifiedAt: timestamp("verified_at", { withTimezone: true }).defaultNow().notNull() });
export const journalEvents = pgTable("journal_events", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), taskId: uuid("task_id").references(() => tasks.id, { onDelete: "set null" }), actor: agentKind("actor").notNull(), eventType: text("event_type").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().default({}).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("journal_project_created_idx").on(t.projectId, t.createdAt)]);
