CREATE TYPE "task_status" AS ENUM ('PLANNED','IN_PROGRESS','CODE_COMPLETE','PR_OPEN','MERGED','DEPLOYED','PROD_VERIFIED','DONE','BLOCKED');
CREATE TYPE "agent_kind" AS ENUM ('CHATGPT','CLAUDE','HUMAN','SYSTEM','OTHER');

CREATE TABLE "projects" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"slug" text NOT NULL UNIQUE,"name" text NOT NULL,"description" text,"github_repo" text,"vercel_project_id" text,"active" boolean DEFAULT true NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "milestones" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"project_id" uuid NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,"name" text NOT NULL,"position" integer DEFAULT 0 NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX "milestones_project_idx" ON "milestones"("project_id");
CREATE TABLE "tasks" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"project_id" uuid NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,"milestone_id" uuid REFERENCES "milestones"("id") ON DELETE SET NULL,"title" text NOT NULL,"description" text,"status" "task_status" DEFAULT 'PLANNED' NOT NULL,"acceptance_criteria" jsonb DEFAULT '[]'::jsonb NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX "tasks_project_idx" ON "tasks"("project_id"); CREATE INDEX "tasks_status_idx" ON "tasks"("status");
CREATE TABLE "agent_runs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"project_id" uuid NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,"task_id" uuid REFERENCES "tasks"("id") ON DELETE SET NULL,"agent" "agent_kind" NOT NULL,"summary" text,"started_at" timestamptz DEFAULT now() NOT NULL,"finished_at" timestamptz);
CREATE TABLE "pull_requests" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"project_id" uuid NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,"task_id" uuid REFERENCES "tasks"("id") ON DELETE SET NULL,"number" integer NOT NULL,"url" text NOT NULL,"head_sha" text,"merged_at" timestamptz,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "deployments" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"project_id" uuid NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,"task_id" uuid REFERENCES "tasks"("id") ON DELETE SET NULL,"provider" text DEFAULT 'vercel' NOT NULL,"external_id" text NOT NULL,"commit_sha" text,"environment" text NOT NULL,"status" text NOT NULL,"deployed_at" timestamptz,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "verifications" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"project_id" uuid NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,"task_id" uuid REFERENCES "tasks"("id") ON DELETE SET NULL,"kind" text NOT NULL,"passed" boolean NOT NULL,"evidence" jsonb DEFAULT '{}'::jsonb NOT NULL,"verified_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "journal_events" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"project_id" uuid NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,"task_id" uuid REFERENCES "tasks"("id") ON DELETE SET NULL,"actor" "agent_kind" NOT NULL,"event_type" text NOT NULL,"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX "journal_project_created_idx" ON "journal_events"("project_id","created_at");
